import nodemailer from 'nodemailer';
import type { QueryFormValues } from './validations';

export async function sendQueryNotification(data: QueryFormValues) {
  const smtpHost = process.env.SMTP_HOST;
  const smtpPort = Number(process.env.SMTP_PORT || 587);
  const smtpUser = process.env.SMTP_USER;
  const smtpPassword = process.env.SMTP_PASSWORD;
  const smtpFrom = process.env.SMTP_FROM;
  const recipientList = process.env.QUERY_NOTIFICATION_EMAILS?.split(',').map((address) => address.trim()).filter(Boolean) ?? [];

  if (!smtpHost || !smtpUser || !smtpPassword || !smtpFrom || recipientList.length === 0) {
    throw new Error('SMTP and recipient configuration must be provided in environment variables.');
  }

  const transporter = nodemailer.createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: smtpPort === 465,
    auth: {
      user: smtpUser,
      pass: smtpPassword
    }
  });

  const subject = `New Website Query — ${data.name}`;
  const html = `<div style="font-family:Inter,sans-serif;color:#111827;line-height:1.6;">
      <h2 style="color:#1f2937;font-size:1.5rem;margin-bottom:0.5rem;">New Enquiry Received</h2>
      <p style="margin:0 0 1rem 0;color:#4b5563;">A new enquiry was submitted via the website.</p>
      <table style="width:100%;border-collapse:collapse;margin-top:1rem;">
        <tbody>
          <tr><td style="padding:0.75rem 0;font-weight:600;width:160px;">Name</td><td style="padding:0.75rem 0;">${escapeHtml(data.name)}</td></tr>
          <tr><td style="padding:0.75rem 0;font-weight:600;">Email</td><td style="padding:0.75rem 0;">${escapeHtml(data.email)}</td></tr>
          <tr><td style="padding:0.75rem 0;font-weight:600;">Phone</td><td style="padding:0.75rem 0;">${escapeHtml(data.phone)}</td></tr>
          <tr><td style="padding:0.75rem 0;font-weight:600;">Party / Group</td><td style="padding:0.75rem 0;">${escapeHtml(data.company || '—')}</td></tr>
          <tr><td style="padding:0.75rem 0;font-weight:600;">Interest</td><td style="padding:0.75rem 0;">${escapeHtml(data.service || '—')}</td></tr>
          <tr><td style="padding:0.75rem 0;font-weight:600;">Submitted from</td><td style="padding:0.75rem 0;">${escapeHtml(data.source || 'website')}</td></tr>
          <tr><td style="padding:0.75rem 0;font-weight:600;">Message</td><td style="padding:0.75rem 0;">${escapeHtml(data.message)}</td></tr>
        </tbody>
      </table>
      <p style="color:#6b7280;font-size:0.95rem;margin-top:1.5rem;">This notification was generated by Vamskidszone website form integration.</p>
    </div>`;

  const text = `New Enquiry Received

Name: ${data.name}
Email: ${data.email}
Phone: ${data.phone}
Party / Group: ${data.company || '—'}
Interest: ${data.service || '—'}
Submitted from: ${data.source || 'website'}

Message:
${data.message}`;

  await transporter.sendMail({
    from: smtpFrom,
    to: recipientList,
    subject,
    text,
    html
  });
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
